# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and deploy pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - .gitignore
    - _config.dev.yml
    - 'bin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://thom4.net/photography/
    steps:
    # Setup
    - uses: actions/checkout@v4
    - run: sudo apt install --no-install-recommends --assume-yes graphicsmagick nasm
    - name: Use Node.js v16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: npm
    - run: npm ci

    # Build
    - run: npm run build
      env:
        NODE_ENV: production

    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_PRIVATE_KEY }}"
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Transfer
      run: rsync --compress --archive --stats --delete ./public/ oncletom@${{ secrets.SSH_HOST }}:./photography/


    # Deploy
    # - name: Install mc
    #   run: |
    #     wget --quiet https://dl.min.io/client/mc/release/linux-amd64/mc
    #     chmod +x mc
    # - name: Setup mc
    #   run: ./mc alias set deuxfleurs https://garage.deuxfleurs.fr "${{ secrets.MINIO_ACCESS_KEY_ID }}" ${{ secrets.MINIO_SECRET_ACCESS_KEY }} --api S3v4

    # - name: Transfer
    #   if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    #   run: ./mc mirror --preserve --overwrite --summary --quiet ./public/ deuxfleurs/thom4.net/photography/
